### ISSUE TITLE
Setup the server

### ISSUE THREAD

**Issue by kphaterp** [UBC-MDS/525-group16#16]

**Comment by NikitaShymberg** [comment]
![image](https://user-images.githubusercontent.com/25651718/162229732-b27d7b78-8f60-452f-8ebc-7833a247a277.png)

**Comment by NikitaShymberg** [comment]
![image](https://user-images.githubusercontent.com/25651718/162231532-9d252b98-f8c5-4536-9946-d307ddc3a437.png)
